name: Hello, World
on: push

jobs: 
  build: 
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: sudo add-apt-repository ppa:longsleep/golang-backports
      - name: Test2
        run: sudo apt update
      # - name: Go Download
      #   run: sudo apt install golang-1.18
      - name: Go Version
        run: go version
